language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - unset GEM_PATH
install:
  - npm install phantomjs -g
  - npm install casperjs -g
  - travis_retry sudo apt-get install -y --fix-missing libmagic1 libmagic-dev
  - gem install pdd
  - gem install est
script:
  - mvn clean install -Pqulice --batch-mode --errors
  - pdd --source=$(pwd) --verbose --file=/dev/null
  - est --dir=est --file=/dev/null
